#debug: true
spring:
    datasource:
        url: jdbc:${DATABASE_URL_NEW}
        # Hikari connection pool
        hikari:
          connection-timeout: 20000
          minimum-idle: 5
          maximum-pool-size: 12
          idle-timeout: 300000
          max-lifetime: 1200000
          auto-commit: true
    jpa:
#      open-in-view: false
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: validate
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              jdbc:
                lob:
                  non_contextual_creation: true
    liquibase:
      url: jdbc:${DATABASE_URL_NEW}
      change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  servlet:
    contextPath: /v1

# logging
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level:
      org.springframework.web: WARN
      org.hibernate: WARN
      org.hibernate.SQL: debug